require 'json'
require 'fileutils'

def read_app_json
  file = File.read("../../app.json")
  data = JSON.parse(file)
  {
    version: data.dig("expo", "version") || "",
    a_version: data.dig("expo", "android", "versionCode") || "",
    ios_bundle_id: data.dig("expo", "ios", "bundleIdentifier") || "",
    android_package: data.dig("expo", "android", "package") || ""
  }
end

def read_languages_json
  file = File.read("../languages.json")
  JSON.parse(file)
end

def read_aso_json
  file = File.read("./aso.json") # Adjust path as needed
  JSON.parse(file)
end

def gather_screens
  screenshots = {}
  Dir.glob("../screens/*.png").each do |path|
    filename = File.basename(path)
    if m = filename.match(/^([a-zA-Z0-9\-]+)_(6\.5|12\.9|13)_(\d+)\.png$/)
      loc, size, idx = m[1], m[2], m[3].to_i
      screenshots[loc] ||= {}
      screenshots[loc][size] ||= []
      screenshots[loc][size] << { idx: idx, path: File.expand_path(path) }
    end
  end
  screenshots
end

app_data = read_app_json
languages_data = read_languages_json
aso_data = read_aso_json

ios_languages = languages_data["app_store"].keys
android_languages = languages_data["play_market"].keys

ios_size_mapping = {
  "6.5" => "iPhone6.5",
  "12.9" => "iPad13",
}

android_size_mapping = {
  "6.5" => ["phoneScreenshots"],
  "12.9" => ["sevenInchScreenshots", "tenInchScreenshots"]
}

default_platform(:ios)

platform :ios do
  lane :upload_metadata_and_screenshots_ios do
    screenshots = gather_screens
    metadata_path = "./metadata"

    # Prepare metadata for each language
    ios_languages.each do |lang|
      lang_data = aso_data["app_store"][lang]
      # Create directory structure for App Store metadata
      lang_dir = "#{metadata_path}/#{lang}"
      FileUtils.mkdir_p(lang_dir)

      # Write metadata files
      File.write("#{lang_dir}/name.txt", lang_data["title"])
      File.write("#{lang_dir}/subtitle.txt", lang_data["subtitle"])
      File.write("#{lang_dir}/keywords.txt", lang_data["keywords"])
      File.write("#{lang_dir}/description.txt", lang_data["description"])

      # Handle screenshots
      ios_size_mapping.each do |size_key, folder_name|
        tmp_dir = "./screenshots/#{lang}"
        FileUtils.mkdir_p(tmp_dir)
        images = nil

        if size_key == "13"
          if screenshots[lang] && screenshots[lang]["13"] && !screenshots[lang]["13"].empty?
            images = screenshots[lang]["13"]
          elsif screenshots[lang] && screenshots[lang]["12.9"] && !screenshots[lang]["12.9"].empty?
            images = screenshots[lang]["12.9"]
          else
            next
          end
        else
          images = screenshots[lang][size_key] if screenshots[lang] && screenshots[lang][size_key]
          next unless images && !images.empty?
        end

        images.sort_by { |s| s[:idx] }.each do |img|
          dest_path = "#{tmp_dir}/#{folder_name}_screenshot#{img[:idx]}.png"
          FileUtils.cp(img[:path], dest_path)
        end
      end
    end

    deliver(
      username: "mykyta.chernenko@gmail.com",
      app_identifier: app_data[:ios_bundle_id],
      app_version: app_data[:version],
      skip_app_version_update: true,
      force: true,
      sync_screenshots: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end
end

platform :android do
  lane :upload_metadata_and_screenshots_android do
    screenshots = gather_screens

    android_languages.each do |lang|
      lang_data = aso_data["play_market"][lang]

      metadata_dir = "./metadata/android/#{lang}"
      FileUtils.mkdir_p(metadata_dir)

      File.write("#{metadata_dir}/title.txt", lang_data["title"])
      File.write("#{metadata_dir}/short_description.txt", lang_data["short_description"])
      File.write("#{metadata_dir}/full_description.txt", lang_data["description"])

      android_size_mapping.each do |size, folder_names|
        next unless screenshots[lang] && screenshots[lang][size]
        folder_names.each do |folder_name|
          tmp_dir = "#{metadata_dir}/images/#{folder_name}"
          FileUtils.mkdir_p(tmp_dir)
          screenshots[lang][size].sort_by { |s| s[:idx] }.each do |img|
            FileUtils.cp(img[:path], "#{tmp_dir}/#{img[:idx]}.png")
          end
        end
      end
    end

    json_key_path = ENV["GOOGLE_PLAY_JSON_KEY_PATH"] || "../google_play_key.json"
    unless File.exist?(json_key_path)
      UI.user_error!("Google Play JSON key file not found at: #{json_key_path}")
    end

    json_key_data = File.read(json_key_path)

    supply(
      skip_upload_apk: true,
      track: "production",
      package_name: app_data[:android_package],
      json_key_data: json_key_data,
      skip_upload_changelogs: true,
      sync_image_upload: true,
      verbose: true
    )
  end
end

lane :upload_all do
  invoke_lane("ios", "upload_metadata_and_screenshots_ios")
  invoke_lane("android", "upload_metadata_and_screenshots_android")
end