const images = [
  require('../../assets/images/content/Image 01.png'),
  require('../../assets/images/content/Image 02.png'),
  require('../../assets/images/content/Image 03.png'),
  require('../../assets/images/content/Image 04.png'),
  require('../../assets/images/content/Image 05.png'),
  require('../../assets/images/content/Image 06.png'),
  require('../../assets/images/content/Image 07.png'),
  require('../../assets/images/content/Image 08.png'),
  require('../../assets/images/content/Image 09.png'),
  require('../../assets/images/content/Image 10.png'),
  require('../../assets/images/content/Image 11.png'),
  require('../../assets/images/content/Image 12.png'),
  require('../../assets/images/content/Image 13.png'),
  require('../../assets/images/content/Image 14.png'),
  require('../../assets/images/content/Image 15.png'),
  require('../../assets/images/content/Image 16.png'),
  require('../../assets/images/content/Image 17.png'),
  require('../../assets/images/content/Image 18.png'),
  require('../../assets/images/content/Image 19.png'),
  require('../../assets/images/content/Image 20.png'),
  require('../../assets/images/content/Image 21.png'),
  require('../../assets/images/content/Image 22.png'),
  require('../../assets/images/content/Image 23.png'),
  require('../../assets/images/content/Image 24.png'),
  require('../../assets/images/content/Image 25.png'),
  require('../../assets/images/content/Image 26.png'),
  require('../../assets/images/content/Image 27.png'),
  require('../../assets/images/content/Image 28.png'),
  require('../../assets/images/content/Image 29.png'),
  require('../../assets/images/content/Image 30.png'),
  require('../../assets/images/content/Image 31.png'),
  require('../../assets/images/content/Image 32.png'),
  require('../../assets/images/content/Image 33.png'),
  require('../../assets/images/content/Image 34.png'),
  require('../../assets/images/content/Image 35.png'),
];

export function getContentImageFromId(id: number) {
  return images[id % 35];
}
